
# Credentials for WebDAV file storage such as SwitchDrive
[webdav]
base_url = "https://drive.switch.ch/remote.php/webdav/"
username = "mcqulat2000@hotmail.com"
password = "TIYNE-CEXMX-OOXBG-UFONT"



